### ISSUE TITLE
Allow BrowserFunction assignments via the Browser class

### ISSUE THREAD

**Issue by quaeler** [maketechnology/chromium.swt#103]
(This issue arose from the KNIME conference call today, 10 Feb, 2020.)

`org.eclipse.swt.chromium.Browser` wraps an instance of `Chromium` which [provides a way to add a JavaScript function](https://github.com/maketechnology/chromium.swt/blob/master/org.eclipse.swt.chromium/src/org/eclipse/swt/chromium/Chromium.java#L192) using `BrowserFunction`. `Browser` provides no way to access the `Chromium` instance so a proxy-method is needed to provide this functionality in `Browser`.

**Comment by tomvdbussche** [comment]
Doesn't creating a new `BrowserFunction` instance handle all this logic?

**Comment by quaeler** [comment]
Yes it does! https://github.com/maketechnology/chromium.swt/blob/master/org.eclipse.swt.chromium/src/org/eclipse/swt/chromium/BrowserFunction.java#L137
