### ISSUE TITLE
Custom arguments for CEF process

### ISSUE THREAD

**Issue by szagorodin** [maketechnology/chromium.swt#16]
Can you add ability to specify custom arguments for CEF GPU process "cefrust_subp.exe"?
I try to use Chromium Browser as SWT control on **windows.x86_64** platform.
On some machines I get black page instead of HTML page.
Errors in log:
`[1109/100403.538:ERROR:gles2_cmd_decoder.cc(15368)] Context lost because SwapBuffers failed.
[1109/100403.538:ERROR:gles2_cmd_decoder.cc(5282)] Error: 5 for Command kPostSubBufferCHROMIUM
[1109/100403.539:ERROR:gpu_channel_manager.cc(218)] Exiting GPU process because some drivers cannot recover from problems.`
It is reproduced with Chromium SWT Demo application.
The problem can be resolved by specifying "--disable-gpu" argument for CEF GPU process.
May be there is another solution?

**Comment by gzunino** [comment]
We already upgrade to newer chromium versions, and probably that is fixed. It's not public yet. It should be soon, with the move of the project to eclipse.
