### ISSUE TITLE
Linux GTK3 support

### ISSUE THREAD

**Issue by nedtwigg** [maketechnology/chromium.swt#17]
The README says only GTK2 is supported currently.  Is GTK3 on the roadmap?  Can/will they be supported concurrently?

**Comment by gzunino** [comment]
It's on the roadmap and likely a must have before merging into SWT. 
In theory we should be able to support both by checking the running GTK and loading the correct libchromium and libcef libraries linked to gtk3, similar to what SWT does.

**Comment by nedtwigg** [comment]
GTK2 is going to be removed entirely from SWT in December 2018 (just 6 months from today):

https://dev.eclipse.org/mhonarc/lists/cross-project-issues-dev/msg15783.html

If SWT is abandoning GTK2 so soon, might be worth doing the same here.

**Comment by laeubi** [comment]
I think it would be good to support older eclipse packages (neon for example), SWT uses an env Variable to switch between GTK2/GTK3

**Comment by gzunino** [comment]
GTK3 is supported in 0.9.0 now. GTK2 has been removed.
