### ISSUE TITLE
focus is constantly shifted between the chromium swt object and the browser itself..

### ISSUE THREAD

**Issue by jcompagner** [maketechnology/chromium.swt#19]
opening the browser works (as an editor tab)
but when i go to another editor and then back
Then it can happen that eclipse completely freezes and it the log i see never ending statements like this:

`<<<<<<<< set_focus 1
J:GetFocusHandler http://localhost:8080/rfb/angular/index.html?s=Test&l=absolute&f=Test&w=640.0&h=480.0&editorid=8df42a0c-5c05-40a5-90fc-c410ef88542d&c_sessionid=ae1e68bd-4ee8-4381-965c-3647a615b4d4
J:CALLBACK OnSetFocus FOCUS_SOURCE_SYSTEM http://localhost:8080/rfb/angular/index.html?s=Test&l=absolute&f=Test&w=640.0&h=480.0&editorid=8df42a0c-5c05-40a5-90fc-c410ef88542d&c_sessionid=ae1e68bd-4ee8-4381-965c-3647a615b4d4
<<<<<<<< set_focus 1
J:GetFocusHandler http://localhost:8080/rfb/angular/index.html?s=Test&l=absolute&f=Test&w=640.0&h=480.0&editorid=8df42a0c-5c05-40a5-90fc-c410ef88542d&c_sessionid=ae1e68bd-4ee8-4381-965c-3647a615b4d4
J:CALLBACK OnSetFocus FOCUS_SOURCE_SYSTEM http://localhost:8080/rfb/angular/index.html?s=Test&l=absolute&f=Test&w=640.0&h=480.0&editorid=8df42a0c-5c05-40a5-90fc-c410ef88542d&c_sessionid=ae1e68bd-4ee8-4381-965c-3647a615b4d4
J:GetFocusHandler http://localhost:8080/rfb/angular/index.html?s=Test&l=absolute&f=Test&w=640.0&h=480.0&editorid=8df42a0c-5c05-40a5-90fc-c410ef88542d&c_sessionid=ae1e68bd-4ee8-4381-965c-3647a615b4d4
J:CALLBACK OnGotFocus http://localhost:8080/rfb/angular/index.html?s=Test&l=absolute&f=Test&w=640.0&h=480.0&editorid=8df42a0c-5c05-40a5-90fc-c410ef88542d&c_sessionid=ae1e68bd-4ee8-4381-965c-3647a615b4d4
J:Forcing focus to SWT canvas: true http://localhost:8080/rfb/angular/index.html?s=Test&l=absolute&f=Test&w=640.0&h=480.0&editorid=8df42a0c-5c05-40a5-90fc-c410ef88542d&c_sessionid=ae1e68bd-4ee8-4381-965c-3647a615b4d4
<<<<<<<< set_focus 1
J:GetFocusHandler http://localhost:8080/rfb/angular/index.html?s=Test&l=absolute&f=Test&w=640.0&h=480.0&editorid=8df42a0c-5c05-40a5-90fc-c410ef88542d&c_sessionid=ae1e68bd-4ee8-4381-965c-3647a615b4d4
J:CALLBACK OnSetFocus FOCUS_SOURCE_SYSTEM http://localhost:8080/rfb/angular/index.html?s=Test&l=absolute&f=Test&w=640.0&h=480.0&editorid=8df42a0c-5c05-40a5-90fc-c410ef88542d&c_sessionid=ae1e68bd-4ee8-4381-965c-3647a615b4d4
<<<<<<<< set_focus 0`

i can fix this by disabling the setFocus() call to the browser instance by changing \

    focusHandler.on_set_focus.set((focusHandler, browser_1, focusSource) -> {
            debugPrint("CALLBACK OnSetFocus " + focusSource);
            if (!isFocusControl() && false) {

in Chromium.java (so adding that false)

Then everything works fine for me, what are we trying to do there?

Why do we call isFocusControl() om the WebBrowser instance which as far as i can see quickly always will return false
And then set the focus to the chromium?
or do we kind of mean that we want todo:  if (!chromium.isFocusControl()
and if that is not the case then transfer the focus to it?
That also seems to work for me

**Comment by gzunino** [comment]
Fixed with 7c10aef8178d5b93a1fe853dc58512b70660289b
