### ISSUE TITLE
command line arguments (or just remote debug startup) support

### ISSUE THREAD

**Issue by jcompagner** [maketechnology/chromium.swt#21]
I read (including in the doc of the CEF or CEFFactory classes that there should be a CefSettings:

		///
		/// Provides an opportunity to view and/or modify command-line arguments before
		/// processing by CEF and Chromium. The |process_type| value will be NULL for
		/// the browser process. Do not keep a reference to the cef_command_line_t
		/// object passed to this function. The CefSettings.command_line_args_disabled
		/// value can be used to start with an NULL command-line object. Any values
		/// specified in CefSettings that equate to command-line arguments will be set
		/// before this function is called. Be cautious when using this function to
		/// modify command-line arguments for non-browser processes as this may result
		/// in undefined behavior including crashes.
		///
		public Function<on_before_command_line_processing> on_before_command_line_processing = function(
				on_before_command_line_processing.class);

But where is that CefSettings class/struct?

so this could be used: https://stackoverflow.com/questions/29117882/debugging-javascript-in-chromium-embedded-framework

or http://magpcss.org/ceforum/viewtopic.php?f=6&t=15099 also talks about on_before_command_line_processing 

but that  doesn't seem to work:

mapTypeForClosure(cef_string_t.class); // first make sure that parameter type is registered
                app.on_before_command_line_processing .set((cef_app_t self_, cef_string_t process_type, jnr.ffi.Pointer command_line) -> {
                	System.err.println(self_);
                	System.err.println(process_type);
                	System.err.println(command_line);
                });

that is never called, and if it was how can i really add/change arguments to

**Comment by jcompagner** [comment]
i see this is kind of a duplicate of #16

**Comment by gzunino** [comment]
Hi Johan ! 
Command line arguments to CEF cannot be configured using the current code.
And I think we should keep it like that, maybe just exposing some well known (I guess debug port is a must one), supported and tested args using system properties or similar. Otherwise it will be a source for bug reports, there are thousands of arguments, some documented others not, which cause all kind of different behaviors and features.

**Comment by jcompagner** [comment]
thats fine by me, i think we need only really to enable the debugger port, because that is a very handy feature to have that you can really debug and see the console output when loading stuff inside eclipse.
