### ISSUE TITLE
no content 

### ISSUE THREAD

**Issue by qq123zhz** [maketechnology/chromium.swt#25]
logs:
cefrust.path: C:\Users\Administrator\.swt\lib\win32\x86_64\chromium-3071
DLL init
subp: "C:\\Users\\Administrator\\.swt\\lib\\win32\\x86_64\\chromium-3071\\chromium_subp-0300.exe"
Calling cef_initialize
J:OnContextInitialized empty url
J:initCef Done empty url
create_browser
create_browser in 1381430
parent 0x151436
Calling cef_browser_host_create_browser
[0803/155641.984:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
J:GetFocusHandler http://www.baidu.com
J:CALLBACK OnSetFocus FOCUS_SOURCE_NAVIGATION http://www.baidu.com
J:Disallowing focus to SWT canvas http://www.baidu.com
J:STARTING MSG LOOP http://www.baidu.com
J:setUrl: https://www.baidu.com http://www.baidu.com
url: "https://www.baidu.com"
J:GetFocusHandler http://www.baidu.com
J:CALLBACK OnSetFocus FOCUS_SOURCE_NAVIGATION http://www.baidu.com
J:Disallowing focus to SWT canvas http://www.baidu.com

no page is show in my shell?

**Comment by erdalkaraca** [comment]
I first tested with google.com as URL and it worked. When using a locally hosted webserver, the shell was empty for me, too.
I realized that when pressing back (in the context menu of the embedded browser), then forward again, my page was rendered.

Seems that the URL is processed before the internal state has been initialized completely?

**Comment by qq123zhz** [comment]
@erdalkaraca  myCode is like that:
 browser = new Browser(parent, SWT.NONE);
  browser.seUrl("www.baidu.com")

how should i do?

**Comment by gzunino** [comment]
CEF version should match the one support by chromium.swt:
https://github.com/maketechnology/chromium.swt/blob/master/org.eclipse.swt.chromium/src/version.properties

For windows, com.make.chromium.cef.win32.win32 jus packages the minimal build from http://opensource.spotify.com/cefbuilds/index.html.

Should work with that version, extracted to ~/.swt

**Comment by gzunino** [comment]
Hi @dstainhauser We are building and delivering with proprietary codecs support for some comercial products, but there are no plans to make it widely available as part of this widget, because it will be against swt project licencing. 
If you are interested please contact me at guillez at gmail dot com
