### ISSUE TITLE
Support for load handlers?

### ISSUE THREAD

**Issue by cpfeiffer** [maketechnology/chromium.swt#26]
It would be awesome if it would be possible to set a handler to implement custom resource loading (even if it's not possible via the standard SWT Browser API).

**Comment by gzunino** [comment]
We are creating an SWT browser implementation and not proving general CEF bindings or new APIs. It's not the intend of this project. 
We are using and providing CEF APIs in other projects and for other usages, but not as part of this open source initiative. If you interested please contact me (guillez at gmail).
