### ISSUE TITLE
Closing a "popup" browser window closes the orignal browser.

### ISSUE THREAD

**Issue by hthomann** [maketechnology/chromium.swt#29]
HI!  Take this HTML that opens a new window:

`<!DOCTYPE` `html>`
`<html>`
`<body>`

`<a` href="https://www.google.com" target="_blank">Click here to visit Google!</a> 

`<p>The` link above will open in a new browser window or a new tab.</p>

`</body>`
`</html>`

I saved this in a file called popup.html.

I have create a view in my eclipse plugin that creates a org.eclipse.swt.chromium.Browser.  With this browser I do a setUrl("file:///E:/popup.html").  I open my view and the popup.html is displayed.  When I click the 'Click here to visit Google' link a new window is opened and google.com loaded.  When I click the X button to close the "popup" browser, the 'parent', or originally opened browser contained in my view is closed.  When I hit the X button a second time, the "popup" browser finally closes.  Is there any way to fix this?  Closing the second ("popup") browser should not close the first browser.  
If you want me to send to you my plugin I will, but all it is a 'sample view' (from the samples templates) created in the Eclipse RCP, where the view instantiates the Browser.  Nothing special at all.

**Comment by hthomann** [comment]
HI!  I just tried this out and things are different, but still not working.  In deed when I close the pop up window it now closes AND the original window is retained.  So that is good.  However, the original window is frozen upon returning to it.  As I mention in my previous post, I have created a view in my eclipse plugin that creates a org.eclipse.swt.chromium.Browser.  Maybe there is something wrong with my view and there needs to be a refresh or something??  Basically, my view looks like:

public class SampleView extends ViewPart {
……
	@Override
	public void createPartControl(Composite parent) {
		Browser b = new Browser(parent,0);
		b.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, true, 1, 1));
		b.setUrl("file:///E:/tmp/popup.html");
	}
……

I can send to you my simple view…..it is a very simple project you can import and execute as an eclipse app.  

For your reference, here is what I see in the console when I open, then close, the popup window:

J1:on_before_popup jnr.ffi.provider.jffi.DirectMemoryIO[address=0x3aa0b350]:null file:///E:/tmp/popup.html
J1:on_after_created jnr.ffi.provider.jffi.DirectMemoryIO[address=0x3aa0ba50]:null file:///E:/tmp/popup.html
J1:on_before_browse file:///E:/tmp/popup.html
J1:on_before_browse:https://www.google.com/ file:///E:/tmp/popup.html
J1:on_after_created handling jnr.ffi.provider.jffi.DirectMemoryIO[address=0x3aa0ba50]:null file:///E:/tmp/popup.html
J1:on_address_change:https://www.google.com/ true file:///E:/tmp/popup.html
J1:on_before_browse file:///E:/tmp/popup.html
J1:on_before_browse:https://ogs.google.com/widget/app/so?hl=en&origin=https%3A%2F%2Fwww.google.com&pid=1&spid=1&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.gapi.en.CUp85wbT4DI.O%2Frt%3Dj%2Fd%3D1%2Frs%3DAHpOoo-XBQda2DFvo9hxbj_dGnCV84SJMA%2Fm%3D__features__#id=I0_1543611491458&_gfid=I0_1543611491458&parent=https%3A%2F%2Fwww.google.com&pfname=&rpctoken=80168224 file:///E:/tmp/popup.html
J1:DoClose popup:jnr.ffi.provider.jffi.DirectMemoryIO[address=0x3aa0d250]:jnr.ffi.provider.jffi.DirectMemoryIO[address=0x3aa0af50] file:///E:/tmp/popup.html
J1:OnBeforeClose file:///E:/tmp/popup.html
freed
J:STOPPING MSG LOOP


By the way, when the browser is initially created, I do see this in logs:

[1130/135802.834:ERROR:main_delegate.cc(714)] Could not load cef_extensions.pak


Not sure if this is related or an issue??

**Comment by gzunino** [comment]
Hi! 
Thanks for the update. I'll take another look, I just saw it passing green in tests, but is clear from the logs what the problem is.

This line
[1130/135802.834:ERROR:main_delegate.cc(714)] Could not load cef_extensions.pak
is not a problem. It should be just a warning but CEF reports as error.
