### ISSUE TITLE
Javascript key handlers are not called after focus change

### ISSUE THREAD

**Issue by rgansevles** [maketechnology/chromium.swt#34]
We have event handlers for shortcut keys in our web application.
When the page is loaded, the key handlers work fine, but when the chromium browser lost and regained focus, the event handlers are not called until the user clicks on the page.

**Expected behaviour**
Key events are handled after focus lost/regained _without_ the user clicking on the page.

_This worked as expected with the 0.5.0 version and is broken in the 0.6.0 and 0.7.0 version_

**Steps to reproduce**

* Compile/run the attached sample java program
* type keys a b c _typed letter is shown in the page_
* type key **d** _an alert dialog is shown_
* close the dialog (click OK) _main window regains focus_ **do not click on the browser window**
* type any key _the key should show on the page but it does not because the event handler is not called_
* click in the browser window
* event handling is restored

**Environment**
Windows 10 Version 1607
org.eclipse.swt.chromium-0.7.0
org.eclipse.swt.chromium.win32.win32.x86_64-0.7.0
org.eclipse.swt.win32.win32.x86_64_3.106.2.v20171129-0543.

**Comment by rgansevles** [comment]
Sample program:
```java
import org.eclipse.swt.SWT;
import org.eclipse.swt.chromium.Browser;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class Main {

    public static void main(String[] args) {
        Display display = new Display();
        Shell shell = new Shell(display);
        shell.setLayout(new FillLayout(SWT.VERTICAL));

        Browser browser = new Browser(shell, SWT.NONE);

        // the key typed is shown on the page.
        // when a 'd' is typed, a dialog is shown which removes the focus
        // when the dialog is closed, the browser gets focus again, but the key handler does not get called until you click into the page.
        browser.setText("<html>" +
                "<script>" +
                "document.addEventListener('keyup',function(e){document.getElementById('p').innerHTML=e.key;if(e.key=='d')alert('test')})" +
                "</script>" +
                "<body><p id='p'>X</p></body>" +
                "</html>");

        shell.setSize(150, 150);
        shell.open();
        while (!shell.isDisposed()) {
            if (!display.readAndDispatch()) {
                display.sleep();
            }
        }
        display.dispose();
    }
} 
```

**Comment by Daan-** [comment]
I still have the same issue with the sample project above. Using versions:

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'org.eclipse', name: 'org.eclipse.swt.chromium', version: '0.9.1.201904260302'
    compile group: 'org.eclipse', name: 'org.eclipse.swt.chromium.win32.win32.x86_64', version: '0.9.1.201904260302'
    compile (group: 'org.eclipse.platform', name: 'org.eclipse.swt.win32.win32.x86_64', version: '3.106.3') {
        exclude group: 'org.eclipse.platform', module: 'org.eclipse.swt'
    }
    implementation 'com.github.jnr:jnr-ffi:2.1.9'
    implementation 'com.github.jnr:jffi:1.2.18'
    implementation 'com.github.jnr:jnr-x86asm:1.0.2.v201505052040'
    implementation 'org.ow2.asm:asm:7.1'
    implementation 'org.ow2.asm:asm-util:7.1'
    implementation 'org.ow2.asm:asm-tree:7.1'
    implementation 'org.ow2.asm:asm-analysis:7.1'
    implementation 'org.ow2.asm:asm-commons:7.1'
}
