### ISSUE TITLE
Browser not loading/rendering in my installed plugin.

### ISSUE THREAD

**Issue by hthomann** [maketechnology/chromium.swt#35]
HI!  I’m going to describe a scenario where the Chromium browser seems to load in my view, but doesn’t seem to render.  My scenario/sample is pretty simple, I’m actually attaching a P2 installable site with my sample.  I create a simple view plugin that instantiates the new Chromium browser and sets and URL.  I then select my plugin and do ‘Run As -> Eclipse Application’.  In the resultant Eclipse I open my view and the Chromium browser is loaded and displays the URL perfectly.  Very awesome!  Note that in the console I see a lot of debug output from your Chromium feature, all looks good.  
The problem is what comes next, that is, I recently exported my plugin as a P2 site, install it, and then opened my view.  In this case, Chromium browser seems to not render and seems hung.  Let me explain those steps a little more.  Basically, I create a feature for my plugin and then export it as a ‘Deployable Features’ (p2 site).  I then install your two Chromium P2 sites, and my P2 site, into a pristine Eclipse Photon JEE.  After install I restart and then open my view.  The view opens but the browser seems to be hung.  In the console I see all the debug output from the Chromium feature as usual which looks normal to me (i.e. no errors).  The browser never seems to render, that is, it doesn’t display the web page and seems to be hung.  So my question is, why does my view and the Chromium browser load/work perfectly when I do a ‘Run As -> eclipse application’, but not when I install the plugin.  My guess is that either my plugin is missing a dependency, or the Chromium feature is missing a dependency.

If you would like to try this out for yourself, I’ve attached my P2 site (MyCEFView.zip attached, source code is there as well).  To use it, please do the following:

1) I got the latest Eclipse Photon JEE and extracted it.

2) I then installed the following two P2 sites (restarting after each install):

http://dl.maketechnology.io/chromium-swt/rls/repository

http://dl.maketechnology.io/chromium-cef/rls/repository

3) I then installed my P2 site (download and extract the attached MyCEFView.zip).  During install uncheck the ‘group items by category’.

4) Restart eclipse (start it from the console so you can see the Chromium debug output).

5) Go to Window -> Show View -> Other… -> Sample Category -> Sample View.  The view will be opened, Chromium debug printed to the console (all looks well), but the view/browser seems to be hung.

If you import my feature instead, then select it, and do ‘Run As – Eclipse Application’, then open the view in the resultant Eclipse, the view and browser works great.  

Could you look at the source of my plugin and see if I’m missing something or if you Chromium plugin is missing something?

Sincerely,
 
Heath Thomann

**Comment by hthomann** [comment]
[MyCEFView.zip](https://github.com/maketechnology/chromium.swt/files/2692692/MyCEFView.zip)

**Comment by gzunino** [comment]
Hi @hthomann would you mind attaching stdout when it doesn't work?

Thanks.

**Comment by hthomann** [comment]
Here is the output when you run MyCEFView and it doens't load/render:


cefrust.path: C:\Users\Heath Thomann\.swt\lib\win32\x86_64\chromium-3071
DLL init
subp: "C:\\Users\\Heath Thomann\\.swt\\lib\\win32\\x86_64\\chromium-3071\\chromium_subp-0700.exe"
Calling cef_initialize
[1226/213432.769:ERROR:main_delegate.cc(714)] Could not load cef_extensions.pak
J1:OnContextInitialized empty url
J1:initCef Done empty url
create_browser in 1315434
parent 0x14126a
Calling cef_browser_host_create_browser
J1:on_after_created jnr.ffi.provider.jffi.DirectMemoryIO[address=0x36fb59b0]:null about:blank
J1:GetFocusHandler about:blank
J1:CALLBACK OnSetFocus FOCUS_SOURCE_NAVIGATION about:blank
J1:STARTING MSG LOOP about:blank
J1:setUrl: http://whatismybrowser.com about:blank
url: "http://whatismybrowser.com"
J1:GetFocusHandler about:blank
J1:CALLBACK OnSetFocus FOCUS_SOURCE_NAVIGATION about:blank
J1:GetFocusHandler about:blank
J1:CALLBACK OnGotFocus about:blank
SampleView.setFocus()
SampleView.setFocus()
J1:on_after_created handling jnr.ffi.provider.jffi.DirectMemoryIO[address=0x36fb59b0]:null http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:http://whatismybrowser.com/ http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://www.whatismybrowser.com/ http://whatismybrowser.com
J1:on_address_change:https://www.whatismybrowser.com/ true http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://googleads.g.doubleclick.net/pagead/html/r20181205/r20180604/zrt_lookup.html# http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://googleads.g.doubleclick.net/pagead/ads?client=ca-pub-8548565564007782&output=html&h=280&twa=0&slotname=7182564424&adk=2900024244&adf=3018905140&w=336&lmt=1545885276&guci=2.2.0.0.2.2.0.0&format=336x280&url=https%3A%2F%2Fwww.whatismybrowser.com%2F&flash=0&wgl=1&dt=1545885276131&bpp=151&bdt=754&fdt=193&idt=191&shv=r20181205&cbv=r20180604&saldr=aa&abxe=1&correlator=4791522954953&frm=20&pv=2&ga_vid=567189644.1545885276&ga_sid=1545885276&ga_hid=712070085&ga_fc=0&iag=0&icsg=138&dssz=7&mdo=0&mso=0&u_tz=-420&u_his=1&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=2&u_nmime=2&adx=624&ady=484&biw=755&bih=491&scr_x=0&scr_y=0&eid=21060853%2C62710015%2C62710017%2C21061976%2C410075081%2C410075101&oid=3&rx=0&eae=0&fc=656&brdim=600%2C221%2C600%2C221%2C1536%2C0%2C773%2C509%2C772%2C508&vis=1&rsz=%7C%7CeE%7C&abl=CS&ppjl=f&pfx=0&fu=1040&bc=13&osw_key=2828523760&ifi=1&uci=1.toqd464d454k&fsb=1&xpc=wuAbW2Xvgc&p=https%3A//www.whatismybrowser.com&dtd=235 http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://googleads.g.doubleclick.net/pagead/ads?client=ca-pub-8548565564007782&output=html&h=600&twa=0&slotname=2818370829&adk=1607965722&adf=2233800847&w=160&lmt=1545885276&guci=2.2.0.0.2.2.0.0&format=160x600&url=https%3A%2F%2Fwww.whatismybrowser.com%2F&flash=0&wgl=1&dt=1545885276373&bpp=26&bdt=995&fdt=27&idt=-M&shv=r20181205&cbv=r20180604&saldr=aa&abxe=1&prev_fmts=336x280&correlator=4791522954953&frm=20&pv=1&ga_vid=567189644.1545885276&ga_sid=1545885276&ga_hid=712070085&ga_fc=0&iag=0&icsg=650&dssz=9&mdo=0&mso=0&u_tz=-420&u_his=1&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=2&u_nmime=2&adx=712&ady=1078&biw=755&bih=491&scr_x=0&scr_y=0&eid=21060853%2C62710015%2C62710017%2C21061976%2C410075081%2C410075101&oid=3&rx=0&eae=0&fc=656&brdim=600%2C221%2C600%2C221%2C1536%2C0%2C773%2C509%2C772%2C508&vis=1&rsz=%7C%7CleEbr%7C&abl=CS&ppjl=f&pfx=0&fu=1040&bc=13&osw_key=4125969423&ifi=2&uci=2.drib2py225vx&fsb=1&xpc=R4AcRhaFXH&p=https%3A//www.whatismybrowser.com&dtd=32 http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://googleads.g.doubleclick.net/pagead/ads?client=ca-pub-8548565564007782&output=html&h=90&slotname=4799716640&adk=2711459071&adf=1697028921&w=728&fwrn=4&fwrnh=100&lmt=1545885276&rafmt=1&guci=2.2.0.0.2.2.0.0&format=728x90&url=https%3A%2F%2Fwww.whatismybrowser.com%2F&flash=0&fwr=0&resp_fmts=3&wgl=1&dt=1545885276410&bpp=13&bdt=1032&fdt=13&idt=-M&shv=r20181205&cbv=r20180604&saldr=aa&abxe=1&prev_fmts=336x280%2C160x600&correlator=4791522954953&frm=20&pv=1&ga_vid=567189644.1545885276&ga_sid=1545885276&ga_hid=712070085&ga_fc=0&iag=0&icsg=650&dssz=10&mdo=0&mso=0&u_tz=-420&u_his=1&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=2&u_nmime=2&adx=116&ady=1797&biw=755&bih=491&scr_x=0&scr_y=0&eid=21060853%2C62710015%2C62710017%2C21061976%2C410075081%2C410075101&oid=3&rx=0&eae=0&fc=656&brdim=600%2C221%2C600%2C221%2C1536%2C0%2C773%2C509%2C772%2C508&vis=1&rsz=%7C%7CeEbr%7C&abl=CS&ppjl=f&pfx=0&fu=1168&bc=13&osw_key=173507840&ifi=3&uci=3.sraqkx3jjab5&fsb=1&xpc=06yOFRRZld&p=https%3A//www.whatismybrowser.com&dtd=18 http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://googleads.g.doubleclick.net/xbbe/pixel?d=CJfKHRCLxXAY9Kb3HzAB&v=APEucNUqS7IQZVq0xFXSfWSttIjjKzopJhJWBqg4ER9oHsF5_ta-oQ8cQTNRx_ZFW4z8vVyii1k4ceGSa5AihH-udNkzzd-dOg http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://googleads.g.doubleclick.net/xbbe/pixel?d=CJfKHRCLxXAY16T3HzAB&v=APEucNXrqTRloCL385BBq1aVkhmKEyjs_QIcfPsS7gg_8U1i_iH-_eoNyllwJBOE2iN03epRJ-8AAOk3GBUxqweduy8MCT68Dw http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://googleads.g.doubleclick.net/xbbe/pixel?d=CJfKHRCLxXAYoab3HzAB&v=APEucNXlguf_yueOPFcASS4QoU2uP6kFpB7E7rzp604zXbClIGFo6yYM5MAvKA6RoKCh-ogL-moT3fq4ii3OI79MbQuxSiD_BA http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://tpc.googlesyndication.com/sodar/6uQTKQJz.html http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://tpc.googlesyndication.com/sodar/6uQTKQJz.html http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://s0.2mdn.net/8032715/1528295654212/index.html http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://s0.2mdn.net/8032715/1528295661084/index.html http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://pagead2.googlesyndication.com/pagead/s/cookie_push.html#aHR0cHM6Ly9pbWFnZTYucHVibWF0aWMuY29tL0FkU2VydmVyL1VDb29raWVTZXRQdWc_b2lkPTEmcmQ9aHR0cHMlM0ElMkYlMkZjbS5nLmRvdWJsZWNsaWNrLm5ldCUyRnBpeGVsJTNGZ29vZ2xlX25pZCUzRHBtZWIlMjZnb29nbGVfc2MlM0QxJTI2Z29vZ2xlX2htJTNEJTIzJTIzQjY0XzE2Ql9QTV9VSUQlMjZnb29nbGVfcmVkaXIlM0RodHRwcyUyNTI1M0ElMjUyNTJGJTI1MjUyRmltYWdlOC5wdWJtYXRpYy5jb20lMjUyNTJGQWRTZXJ2ZXIlMjUyNTJGSW1nU3luYyUyNTI1M0ZzZWMlMjUyNTNEMSUyNTI1MjZwJTI1MjUzRDE1NjU3OCUyNTI1MjZwdSUyNTI1M0RodHRwcyUyNTI1MjUzQSUyNTI1MjUyRiUyNTI1MjUyRmltYWdlNC5wdWJtYXRpYy5jb20lMjUyNTI1MkZBZFNlcnZlciUyNTI1MjUyRlNQdWclMjUyNTI1M0ZwJTI1MjUyNTNEMTU2NTc4JTI1MjUyNTI2c2MlMjUyNTI1M0QxJmdvb2dsZV9naWQ9Q0FFU0VETElBWmFHWWQ5ajhjSHJpeXlicEtBJmdvb2dsZV9jdmVyPTEmZ29vZ2xlX3B1c2g9QUhORjEzTG50OHZ4OEJ1MmRSdjZJWEE3dW9WN3l5Y0ZBZGc2WU8yUHVWN0VCZw==,aHR0cHM6Ly9jbS5nLmRvdWJsZWNsaWNrLm5ldC9waXhlbC9hdHRyP2Q9QUhORjEzSW1EZzZoNURHSDRTa3VsRHVYdnZ2M0VnMm9oSkdo http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://tpc.googlesyndication.com/sodar/EAP3yzUF.html http://whatismybrowser.com
[1226/213442.747:INFO:CONSOLE(0)] "The resource https://pagead2.googlesyndication.com/pagead/js/r20181205/r20180604/show_ads_impl.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.", source: https://www.whatismybrowser.com/ (0)
J1:disposing chromium http://whatismybrowser.com
J1:call close_browser http://whatismybrowser.com
J1:OnBeforeClose http://whatismybrowser.com
freed
J:STOPPING MSG LOOP

**Comment by hthomann** [comment]
Here is the output when you import MyCEFView, select it, do Run As -> Eclipse Application, then open my Sample View (i.e. when things work as expected):

cefrust.path: C:\Users\Heath Thomann\.swt\lib\win32\x86_64\chromium-3071
DLL init
subp: "C:\\Users\\Heath Thomann\\.swt\\lib\\win32\\x86_64\\chromium-3071\\chromium_subp-0700.exe"
Calling cef_initialize
[1226/215352.032:ERROR:main_delegate.cc(714)] Could not load cef_extensions.pak
J1:OnContextInitialized empty url
J1:initCef Done empty url
create_browser in 722530
parent 0xb0662
Calling cef_browser_host_create_browser
J1:on_after_created jnr.ffi.provider.jffi.DirectMemoryIO[address=0x3a3c22a0]:null about:blank
J1:GetFocusHandler about:blank
J1:CALLBACK OnSetFocus FOCUS_SOURCE_NAVIGATION about:blank
J1:STARTING MSG LOOP about:blank
J1:setUrl: http://whatismybrowser.com about:blank
url: "http://whatismybrowser.com"
J1:GetFocusHandler about:blank
J1:CALLBACK OnSetFocus FOCUS_SOURCE_NAVIGATION about:blank
J1:GetFocusHandler about:blank
J1:CALLBACK OnGotFocus about:blank
SampleView.setFocus()
21:53:52.444 [Worker-5: Loading available Gradle versions] INFO  c.g.t.t.d.PublishedGradleVersions - Gradle version information cache is up-to-date. Trying to read.
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:http://whatismybrowser.com/ http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://www.whatismybrowser.com/ http://whatismybrowser.com
J1:on_after_created handling jnr.ffi.provider.jffi.DirectMemoryIO[address=0x3a3c22a0]:null http://whatismybrowser.com
J1:on_address_change:https://www.whatismybrowser.com/ true http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://googleads.g.doubleclick.net/pagead/html/r20181205/r20180604/zrt_lookup.html# http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://googleads.g.doubleclick.net/pagead/ads?client=ca-pub-8548565564007782&output=html&h=280&twa=1&slotname=7182564424&adk=3866114504&adf=3018905140&w=131&fwrn=4&fwrnh=100&lmt=1545886434&guci=2.2.0.0.2.2.0.0&format=131x280&url=https%3A%2F%2Fwww.whatismybrowser.com%2F&flash=0&fwr=0&rh=280&rw=131&wgl=1&dt=1545886434436&bpp=121&bdt=52&fdt=158&idt=156&shv=r20181205&cbv=r20180604&saldr=aa&abxe=1&correlator=7352578277857&frm=20&pv=2&ga_vid=1054169134.1545886435&ga_sid=1545886435&ga_hid=1634066665&ga_fc=0&iag=0&icsg=138&dssz=7&mdo=0&mso=0&u_tz=-420&u_his=1&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=2&u_nmime=2&adx=624&ady=484&biw=755&bih=463&scr_x=0&scr_y=0&eid=10573695%2C21060853%2C410075081&oid=3&rx=0&eae=0&fc=656&brdim=113%2C181%2C113%2C181%2C1536%2C0%2C773%2C480%2C772%2C480&vis=1&rsz=%7C%7CeEbr%7C&abl=CS&ppjl=f&pfx=0&fu=1040&bc=13&osw_key=3192440123&ifi=1&uci=1.afd2fggqywpc&fsb=1&xpc=Gqpn5Prvhy&p=https%3A//www.whatismybrowser.com&dtd=196 http://whatismybrowser.com
[1226/215354.642:INFO:CONSOLE(1)] "Uncaught TagError: adsbygoogle.push() error: No slot size for availableWidth=43", source: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js (1)
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://googleads.g.doubleclick.net/pagead/ads?client=ca-pub-8548565564007782&output=html&h=90&slotname=4799716640&adk=2711459071&adf=1697028921&w=728&fwrn=4&fwrnh=100&lmt=1545886434&rafmt=1&guci=2.2.0.0.2.2.0.0&format=728x90&url=https%3A%2F%2Fwww.whatismybrowser.com%2F&flash=0&fwr=0&resp_fmts=3&wgl=1&dt=1545886434643&bpp=11&bdt=260&fdt=13&idt=-M&shv=r20181205&cbv=r20180604&saldr=aa&abxe=1&prev_fmts=131x280&correlator=7352578277857&frm=20&pv=1&ga_vid=1054169134.1545886435&ga_sid=1545886435&ga_hid=1634066665&ga_fc=0&iag=0&icsg=650&dssz=10&mdo=0&mso=0&u_tz=-420&u_his=1&u_java=0&u_h=864&u_w=1536&u_ah=864&u_aw=1536&u_cd=24&u_nplug=2&u_nmime=2&adx=116&ady=1797&biw=755&bih=463&scr_x=0&scr_y=0&eid=10573695%2C21060853%2C410075081&oid=3&rx=0&eae=0&fc=656&brdim=113%2C181%2C113%2C181%2C1536%2C0%2C773%2C480%2C772%2C480&vis=1&rsz=%7C%7CeEbr%7C&abl=CS&ppjl=f&pfx=0&fu=1168&bc=13&osw_key=173507840&ifi=2&uci=2.ux0bl2bd39nf&fsb=1&xpc=UlIGC7XSYK&p=https%3A//www.whatismybrowser.com&dtd=17 http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://ad.doubleclick.net/ddm/adi/N9515.1835093QUANTCAST.COMADVERT/B20743674.214589098;dc_ver=45.119;sz=728x90;u_sd=1.25;dc_adk=2847542558;ord=57j3bn;click=https%3A%2F%2Fadclick.g.doubleclick.net%2Faclk%3Fsa%3Dl%26ai%3DCzhki4lokXJaSHcXokwOP06rwCN_Q1LBN3r23lq8BwI23ARABIABgyZb2jYSl3BeCARdjYS1wdWItODU0ODU2NTU2NDAwNzc4MqAB0JTA8wPIAQmoAwGqBLYBT9BoY09d_U1fsClMj8F-9mHitP-a2-NvfS10U9exwtDtkVHDDEzaaDCy8Ib7lRrIFhDnniHJuWVWxfnJRQhRksyQRKUtgb6OuNakDQ-pO-7Hg_y9DkilCBC4Ph2nwYdI6PYvVaH_r90kAj4iNOvziS__5cbJiliuF4hlJ4xMp1O9ctgAa_nvo_E1CApMCdIoRLEZK5bCupKaQekVIC8SGnSAT-DMrMV1J9er3nxs3H2itca9GsGABumw5cyjpMKC9wGgBiGoB6a-G6gH2csbqAfPzBvYBwDSCAUIgGEQAQ%26num%3D1%26sig%3DAOD64_33K7QBaFnNHm9hfvOWCQn7EGcx-Q%26client%3Dca-pub-8548565564007782%26adurl%3Dhttp%3A%2F%2Fexch.quantserve.com%2Fr%3Fa%3Dp-f83mnHGect3fW%26labels%3D_qc.clk%2C_click.adserver.rtb%2C_click.rand.31%26rtbip%3D192.184.70.216%26rtbdata2%3DEAAaK1BsYW5uZWRQYXJlbnRob29kRk9BX05ld0RvX1E0XzIwMThfRGVjZW1iZXIg6eYrKPa7IDCNjFA6H2h0dHBzOi8vd3d3LndoYXRpc215YnJvd3Nlci5jb21aKDhpYmVoZjUyMTRucWZOYU1waWZDamFRbmpJX3FjdF9aX3lTNXlNd3B1NOWNPYABwv6Nhg2gAQGoAZnkjwS6AR1DQUVTRURGeGF6ay03M09CS09jTGFZQ29BUEU6McABv-wOyAHpiYzw_izaARZYQ1JhNGdBSFNSWUtaUFJGamdxcGp35QGgr5A_6AFkmALc7iaoAgWoAgawAgi6AgTAuEbYwAICyAIA0ALlsrfj49Sbp-4B4AIA-AIAigMWMS5wdWItODU0ODU2NTU2NDAwNzc4MpIDATGYAwA%26gdpr%3D0%26gdpr_consent%3DBAAAAAAAAAAAAABABBktB86AAAAAEA%26redirecturl2%3D;dc_rfl=2,https%3A%2F%2Fwww.whatismybrowser.com$2,https%3A%2F%2Fwww.whatismybrowser.com%2F$0;xdt=1;crlt=Oa.99hLR6f;osda=2;sttr=60;prcl=s? http://whatismybrowser.com
J1:on_before_browse http://whatismybrowser.com
J1:on_before_browse:https://tpc.googlesyndication.com/sodar/6uQTKQJz.html http://whatismybrowser.com
[1226/215359.409:INFO:CONSOLE(0)] "The resource https://pagead2.googlesyndication.com/pagead/js/r20181205/r20180604/show_ads_impl.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.", source: https://www.whatismybrowser.com/ (0)
SampleView.setFocus()
J1:disposing chromium http://whatismybrowser.com
J1:call close_browser http://whatismybrowser.com
J1:OnBeforeClose http://whatismybrowser.com
freed
J:STOPPING MSG LOOP

**Comment by hthomann** [comment]
Please do let me know if there is anything else you need.  Performing the 5 steps I listed in my opening comments should allow you to see the issue.  If you try it and don't see the issue, please let me know the steps you followed as that would likely offer clues if I'm doing something wrong.

**Comment by hthomann** [comment]
HI!  Any updates on this?  I'm hoping I'm just doing something silly here.......surely someone has tried, and been successful, using this in a plugin??

**Comment by gzunino** [comment]
@hthomann  could you test with new version 0.8.0 just published. Thanks

**Comment by hthomann** [comment]
[MySwtExample.zip](https://github.com/maketechnology/chromium.swt/files/2819910/MySwtExample.zip)

**Comment by hthomann** [comment]
@gzunino HI!  I updated my eclipse with your latest updates.  I then ran the test steps as I described back on December 18th.  Sadly, I see the same issue.  My test is really easy to try, could you please try it so you can see what I see.  Surely providing a feature/plugin that makes use of the browser is going to be the normal path, not one where a user has to do ‘run as’ on an app that uses browser.

Having said that, I followed your SWT Browser example here:

https://github.com/maketechnology/chromium.swt#run-swt-browser-example

I got this running just fine.  Therefore, with the org.eclipse.swt.examples.* plugins created, I then created a feature which contains these plugin.  I did a: New -> Other… -> Plug-in Development -> Feature Project -> Next, I then gave the project a name and hit Next, then added all org.eclipse.swt.examples.* to my feature and hit finish).  I then selected my newly created feature project, right clicked it, selected Export, then Plug-in Development, then Deployable Feature.  I hit next and entered a destination and some options in the options tab.  After that, I went to my Photon Eclipse that has your two P2 sites installed, and installed the feature I just exported.  Once installed I restart my Photon Eclipse and do Show View -> Other.. and search for Web Browser, then select it.  The view opens, but again, seems to be hung (doesn’t render the page).  I see the exact same behavior I described at the opening of this issue.  Why can’t I do this?  This would seem to be the most common path.  Over time folks are going to want to create features/plugins that make use of the Browser.
I uploaded this feature.  It is named MySwtExample.zip.  Can you please take a look at this?

Sincerely,

Heath Thomann

**Comment by hthomann** [comment]
HI!  Any updates here?  I've provided two samples, one based off of the sample you document in your github.  Exporting a plugin/feature that makes use of your browser would seem like a normal path.  Thank you!!

**Comment by dstainhauser** [comment]
It might be a matter of your Microsoft Windows zoom scale. We observed that on Windows HDPI displays, the browser stays blank, but has the full HTML set. Try setting the display zoom to 100%, relog into Windows and restart your test case. Interestingly, on one of our developer machines, this behavior can only be observed with a packaged RCP app, not when run from the Eclipse workspace.

This is definitely a bug that has to be solved.

**Comment by gzunino** [comment]
@hthomann please retry with 0.9.0. I think it may work now.

**Comment by hthomann** [comment]
Yep, it seems to be working now on 0.9.0!  Thanks!!
