### ISSUE TITLE
A second window is shown on Linux

### ISSUE THREAD

**Issue by rgansevles** [maketechnology/chromium.swt#37]
When the chromium browser is started on Linux, the browser is opened and another grey window as well.
Resizing this window resizes the browser window as well.

See the sample program in issue https://github.com/maketechnology/chromium.swt/issues/34

Running the same code with the swt browser (webkit) only shows the browser window.

**Environment**
Ubuntu 18.04.1 LTS
com.make.chromium.cef.gtk.linux.x86_64_0.3.0.201807050001
org.eclipse.swt_3.107.0.v20180611-0422
org.eclipse.swt.gtk.linux.x86_64_3.107.0.v20180611-0422
org.eclipse.swt.chromium_0.7.0.201811300653
org.eclipse.swt.chromium.gtk.linux.x86_64_0.7.0.201811300653

**Comment by gzunino** [comment]
Hi @rgansevles I think this is fixed with 0.8.0, could you retest please? Thanks,

**Comment by gzunino** [comment]
Fixed on 0.8.0
