### ISSUE TITLE
No javascript dialog on Linux

### ISSUE THREAD

**Issue by rgansevles** [maketechnology/chromium.swt#38]
window.alert() does not show a popup on Linux.

Instead, a message is logged:
> [1226/223828.668051:WARNING:javascript_dialog_manager.cc(122)] No javascript dialog runner available for this platform

See the sample program in issue https://github.com/maketechnology/chromium.swt/issues/34
Hit the 'd' key in the browser window, it should show a dialog.

Running the same code with the swt browser (webkit) does give a javascript dialog.

**Environment**
Ubuntu 18.04.1 LTS
com.make.chromium.cef.gtk.linux.x86_64_0.3.0.201807050001
org.eclipse.swt_3.107.0.v20180611-0422
org.eclipse.swt.gtk.linux.x86_64_3.107.0.v20180611-0422
org.eclipse.swt.chromium_0.7.0.201811300653
org.eclipse.swt.chromium.gtk.linux.x86_64_0.7.0.201811300653

**Comment by gzunino** [comment]
@rgansevles  the CEF implementation skips default alerts in linux. We still need to add that piece.
