### ISSUE TITLE
Callback with empty string causing browser failure

### ISSUE THREAD

**Issue by parg** [maketechnology/chromium.swt#41]
Windows 7, 64 bit
JDK 1.8.0_121
SWT: 4.922
chromium.swt: master
jnr-ffi: 2.1.9
jffi: 1.2.18
asm: 7.0
CEF Version:      3.3071.1649.g98725e6
Chromium Verison: 59.0.3071.109

A callback with an argument of '' causes the browser to turn into a grey-screen-of-death.

To reproduce simply take the existing basic callback test and add '' to the invocation:

@Test
public void test_BrowserFunction_callback () {
	// On webkit1, this test works if ran on it's own. But sometimes in test-suite with other tests it causes jvm crash.
	// culprit seems to be the main_context_iteration() call in shell.setVisible().
	// See Bug 509587.  Solution: Webkit2.
	assumeFalse(webkit1SkipMsg(), isWebkit1);

	AtomicBoolean javaCallbackExecuted = new AtomicBoolean(false);

	class JavascriptCallback extends BrowserFunction { // Note: Local class defined inside method.
		JavascriptCallback(Browser browser, String name) {
			super(browser, name);
		}

		@Override
		public Object function(Object[] arguments) {
			javaCallbackExecuted.set(true);
			return null;
		}
	}

	String htmlWithScript = "<html><head>\n"
			+ "<script language=\"JavaScript\">\n"
			+ "function callCustomFunction() {\n"  // Define a javascript function.
			+ "     document.body.style.backgroundColor = 'red'\n"
			+ "		jsCallbackToJava('')\n"        // CHANGED HERE!
			+ "}"
			+ "</script>\n"
			+ "</head>\n"
			+ "<body> I'm going to make a callback to java </body>\n"
			+ "</html>\n";

	browser.setText(htmlWithScript);
	new JavascriptCallback(browser, "jsCallbackToJava");

	browser.addProgressListener(callCustomFunctionUponLoad);

	shell.open();
	boolean passed = waitForPassCondition(javaCallbackExecuted::get);
	String message = "Java failed to get a callback from javascript. Test timed out";
	assertTrue(message, passed);
}

**Comment by gzunino** [comment]
Hi @parg I think this is fixed with 0.8.0, Please re test and close or comment, thanks.

**Comment by parg** [comment]
I grabbed the latest and re-ran your unit tests. I'm seeing a few of the callback tests fail that didn't fail before:

test_BrowserFunction_callback_with_javaReturningInt
test_BrowserFunction_callback_and_execute
test_BrowserFunction_callback_with_javaReturningArray
test_BrowserFunction_callback_with_javaReturningString
test_BrowserFunction_callback_afterPageReload

my previous issue with a callback of '' is still failing.

Perhaps I did something wrong when picking up 0.8 ?

**Comment by gzunino** [comment]
@parg the empty string arg issue is fixed on 0.8.1 (just published)
 Not sure why you got those failing tests, those are passing on win10, linux and mac.
