### ISSUE TITLE
New scaling problem on Mac with 0.8.1, everything x2 in size

### ISSUE THREAD

**Issue by dstainhauser** [maketechnology/chromium.swt#44]
There is a new problem with 0.8.1, that was not present on 0.7

All web-views are scaled by times 2. This happens on macOS with Retina displays.

Here is a view to show the problem when opening google in a webView

<img width="891" alt="screenshot 2019-01-31 at 18 43 53" src="https://user-images.githubusercontent.com/1434584/52073606-3535a980-2588-11e9-9c2c-970715506963.png">

**Comment by dstainhauser** [comment]
This problem happens with setText and with setUrl, both new with 0.8.1

**Comment by dstainhauser** [comment]
Any news on this subject? We would be glad to have a fix for this new problem soon. Thanks.

**Comment by gzunino** [comment]
Hi @dstainhauser I couldn't find any suspect code change between 7.0 and 8.0 which may cause this. The only thing is this: https://github.com/maketechnology/chromium.swt/commit/75b3aa9ab9fdca5bc73b45c4d465bfec32617f2d#diff-aab5ea14f8b2afbc9881191650a0dd59R461 but it's actually the same as was happening before in a different place. Unfortunatly I dont't have a mac with hidpi to test this now. I'll get one in a few weeks in order to try some code changes.

**Comment by dstainhauser** [comment]
Hi Guillermo

It's hard to say what caused the regression. 0.7 was just fine on every Mac, 0.8.1 has everything twice as big. It doesn't matter if the page is shown by setUrl or setText. The same result.

Could it be something with the size of the control itself?

I could run some tests on the mac that may help you to identify the cause. You may send me any testcase and I will immediately return you the results.

**Comment by gzunino** [comment]
@dstainhauser  could you try moving this line: 
https://github.com/maketechnology/chromium.swt/blob/master/org.eclipse.swt.chromium/src/org/eclipse/swt/chromium/Chromium.java#L532
after
https://github.com/maketechnology/chromium.swt/blob/master/org.eclipse.swt.chromium/src/org/eclipse/swt/chromium/Chromium.java#L406

**Comment by dstainhauser** [comment]
Hi Guillermo

I'v removed the first line and added it at the end, here

`   private void createBrowser() {
        if (this.url == null) {
            this.url = "about:blank";
        }
        prepareBrowser();
        final Display display = chromium.getDisplay();
        final Color bgColor = display.getSystemColor(SWT.COLOR_WIDGET_BACKGROUND);
        int cefBgColor = cefColor(bgColor.getAlpha(), bgColor.getRed(), bgColor.getGreen(), bgColor.getBlue());

        final org.eclipse.swt.graphics.Point size = getChromiumSize();
        lib.cefswt_create_browser(hwnd, url, clientHandler, size.x, size.y, jsEnabledOnNextPage ? 1 : 0, cefBgColor);
        lib.cefswt_resized(browser, size.x,  size.y);
    }`

But still the same result. Interestingly, when displaying a web page with position absolute coordinates, the page renders correctly in width and height.

**Comment by gzunino** [comment]
TEsted on several mac, windows and linux with standard and hidpi and seems to work fine now
