### ISSUE TITLE
New encoding problem with 0.8.1

### ISSUE THREAD

**Issue by dstainhauser** [maketechnology/chromium.swt#45]
There is a new problem with the encoding of web pages since 0.8.1, that worked fine with 0.7.
Tested on macOS and Windows, same problem

The html has the correct encoding, but still it gets wrong chars

```
<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <base href="http://bundle/icons/" />
        <meta http-equiv="Content-Style-Type" content="text/css" />
        <meta name='viewport' content='initial-scale=1.0, maximum-scale=1.0' />
        <meta content="http://www.w3.org/1999/xhtml; charset=utf-8" http-equiv="Content-Type" />

```

<img width="511" alt="image" src="https://user-images.githubusercontent.com/1434584/52073910-f2c09c80-2588-11e9-8215-55bd89677534.png">

**Comment by gzunino** [comment]
Are you using `setUrl` or `setText` to load the page? We changed the setText implementation to load faster on browser creation and not after creation as it was before.

**Comment by dstainhauser** [comment]
We are using setText. setUrl is still fine.

**Comment by dstainhauser** [comment]
Any news on this subject? We would be glad to have a fix for this new problem soon. Thanks.
