### ISSUE TITLE
Provide self contained repositories

### ISSUE THREAD

**Issue by laeubi** [maketechnology/chromium.swt#47]
It would be good if the Update sites would include the required dependencies (jnr.ffi, jnr.x86asm as far as I can see) like described here:
https://wiki.eclipse.org/Tycho/eclipse-repository#Creating_a_self-contained_p2_repository

**Comment by gzunino** [comment]
This is not desired, as those dependencies are already available on eclipse repositories.

**Comment by laeubi** [comment]
They are available, but it makes it very hard to use the chromium package outside this very limited setup. Because the update site requires a specific Eclipse repository just to fetch some dependencies that are not features, you are forced to use the "planner" mode what makes it impossible in some cases to combine this with other eclipse versions or custom target platforms that contain conflicting dependencies.

So until chromium swt is integrated into the swt package, a self-contained update would
- improve integration in different setups
- speed up resolution of update site since slicer-mode can be used and not the whole eclipse update-site must be loaded
- guard against changes in external (eclipse) update-site
- Simplifies setup since only one updatesite is required.
