### ISSUE TITLE
Cant type into textfield

### ISSUE THREAD

**Issue by laeubi** [maketechnology/chromium.swt#48]
1) Open https://github.com/login in the browser
2) try to enter username or password -> nothing happens

Seem to be a focus issue, Using shortkey (SHIFT+POS1) inside another textfield (e.g. google search page) makes the mouse unusable

The log is hung with
```
J1:main:CALLBACK OnGotFocus (https://google.de)
J1:main:GetFocusHandler (https://google.de)
J1:main:CALLBACK OnGotFocus (https://google.de)
J1:main:GetFocusHandler (https://google.de)
```
Only Solution seem to kill the App with ALT+F4

**Comment by gzunino** [comment]
Fixed on 0.9.0.

Thanks
