### ISSUE TITLE
Add a license when installing the P2s

### ISSUE THREAD

**Issue by hthomann** [maketechnology/chromium.swt#51]
When installing the P2 repositories the license screen contains no license.  Have you all considered a license yet and if so when will it be available?

**Comment by gzunino** [comment]
Hi, the chromium widget is EPL 2.0 as this is going to be contributed to eclipse swt.

The CEF binaries repositories has "No License" for now, and is only provided in binary form. We are allowing usage of it to simplify the consumption of the chromium widget. How this will remain is unknown at the moment and it will probably depend on the decisions of eclipse swt project, is this contains binaries from other projects.
