### ISSUE TITLE
mvn build error

### ISSUE THREAD

**Issue by gascani** [maketechnology/chromium.swt#52]
Hi,
I've got an error on build project with maven:

It seems than there is no pom.xml in the child modules: 

- org.eclipse.swt.chromium
- org.eclipse.swt.chromium.feature

C:\git\external\chromium.swt>mvn clean dist
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.eclipse:swt.chromium:0.8.1-SNAPSHOT (C:\git\external\chromium.swt\pom.xml) has 2 errors
[ERROR]     Child module C:\git\external\chromium.swt\org.eclipse.swt.chromium\pom.xml of C:\git\external\chromium.swt\pom.xml does not exist
[ERROR]     Child module C:\git\external\chromium.swt\org.eclipse.swt.chromium.feature\pom.xml of C:\git\external\chromium.swt\pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
C:\git\external\chromium.swt>

**Comment by gzunino** [comment]
It uses pomless tycho builds which requires maven 3.3 at least. See https://wiki.eclipse.org/Tycho/Release_Notes/0.24#POM-less_Tycho_builds for requirements.
