### ISSUE TITLE
Near production quality, please update

### ISSUE THREAD

**Issue by dstainhauser** [maketechnology/chromium.swt#53]
Hi dear team at maketechnology

You did such a great job with the long demanding integration of a state of the art HTML5 browser into eclipse. The current development can almost be used for any application. Unfortunately, there are some really nasty and blocking bugs in the version 0.8.1, some of them are new, that were already working with 0.7.

I'd really like to encourage your team to solve these blocking issues, as then the RCP developers could start using Chromium for there applications.

From our point of view, those are the most severe bugs:

#45: New encoding problem with 0.8.1
#44 New scaling problem on Mac with 0.8.1, everything x2 in size
#42 Crashes with EXCEPTION_ACCESS_VIOLATION (0xc0000005): 
#49 Menu context not implemented

Could you please try fixing them and release a new version. We would also prefer the log level to warn instead of debug.

Many thanks for your update. We really would appreciate it.

Daniel

**Comment by hthomann** [comment]
I'd argue this is of utmost importance as well:

https://github.com/maketechnology/chromium.swt/issues/35

If a person can't create their own features/plugins that makes use of the Chromium stuff, and then export those features/plugins as an installable P2 site, how is this close to production ready?  The scenario I describe in issue #35 is pretty simple and basic.  So simple I'm likely missing something.  If another set of eyes can take a quick look at my scenario that would be great!!  :)

Sincerely,

Heath Thomann

**Comment by gzunino** [comment]
All issues are fixed here
