### ISSUE TITLE
Browser function issue

### ISSUE THREAD

**Issue by parg** [maketechnology/chromium.swt#57]
I updated to 0.9 and ran some tests - I am now seeing an issue with a browser function that I've not seen before. I modified an existing unit test to show the problem. I have an existing page that we use for donations withing BiglyBT - it has a callback to a function called 'sendDonationEvent'. Normally two calls are made to it, one to indicate the preferred size of the browser, the second to inform that the page loaded.

If you run the test below the first callback occurs but then second doesn't and the web page subsequently fails to load.

If you remove the ``new JavascriptCallback(browser, "sendDonationEvent");`` then the page loads fine. Something to do with that adding that callback is breaking the browser :(

Place a breakpoint at the final assertTrue(...) call so that you can observe the browser before it gets disposed.

```@Test
public void test_BrowserFunction_callback () {
	// On webkit1, this test works if ran on it's own. But sometimes in test-suite with other tests it causes jvm crash.
	// culprit seems to be the main_context_iteration() call in shell.setVisible().
	// See Bug 509587.  Solution: Webkit2.
	assumeFalse(webkit1SkipMsg(), isWebkit1);

	AtomicBoolean javaCallbackExecuted = new AtomicBoolean(false);

	class JavascriptCallback extends BrowserFunction { // Note: Local class defined inside method.
		JavascriptCallback(Browser browser, String name) {
			super(browser, name);
		}

		@Override
		public Object function(Object[] arguments) {
			javaCallbackExecuted.set(true);
			return null;
		}
	}	
	new JavascriptCallback(browser, "sendDonationEvent");	

	browser.setUrl( "https://www.biglybt.com/donation/donate.php" );
	
	browser.addProgressListener(callCustomFunctionUponLoad);

	shell.open();
	boolean passed = waitForPassCondition(javaCallbackExecuted::get);
	String message = "Java failed to get a callback from javascript. Test timed out";
	assertTrue(message, passed);
}

**Comment by gzunino** [comment]
Hi, I couldn't reproduce the problem. Tested on linux, windows and mac. See screenshot: 
![VirtualBox_Windows_10_Pro_25_04_2019_20_49_07](https://user-images.githubusercontent.com/2495175/56777582-c348b700-67a8-11e9-8123-cafb58a0cd7d.png)

The two stderr lines (red) are printed from the sendDonationEvent browser function, and the page loads correctly.
Could you retry with 0.9.1, there were some problems in the binaries and also in browser function with 0.9.0

**Comment by parg** [comment]
Tried 0.9.1 - same result. I give up :(

**Comment by parg** [comment]
Can I verify that things should work ok with

asm 7.1
jffi 1.2.18
jnr 2.1.9

and 3071 from

http://opensource.spotify.com/cefbuilds/cef_binary_3.3071.1649.g98725e6_windows64.tar.bz2

on Windows 7 64-bit ?

**Comment by gzunino** [comment]
you can use http://opensource.spotify.com/cefbuilds/cef_binary_3.3071.1649.g98725e6_windows64.tar.bz2
I'm using older versions from asm and jnr, I'll try with you exact versions to see if I can reproduce the problem

**Comment by gzunino** [comment]
@parg  new version 0.10.0 remves JNR and fixes many issues. I cant reproduce this. Please use our CEF p2 reposor make sure you dont use DEBUG version of CEF binaries.
