### ISSUE TITLE
Retain old versions in p2 repo

### ISSUE THREAD

**Issue by danieltmartin** [maketechnology/chromium.swt#67]
It looks like only the latest version of chromium.swt is available in the p2 repo. This makes it impossible to have reproducible builds if I'm depending on that p2 repo, i.e. whenever a new version is released, any older version of an RCP product that depends on it can no longer be built. If it is switched to a composite repo with child repos for each version, then that would no longer be a problem.

https://stackoverflow.com/questions/20951842/combine-aggregate-eclipse-p2-repositories-extendable-p2-repository

**Comment by gzunino** [comment]
@danieltmartin  we do provide this in commercial versions of the widget but not in open source version. This repo is likely temporal until it gets merged in swt project
