### ISSUE TITLE
Eclipse version

### ISSUE THREAD

**Issue by Falafelrollo** [maketechnology/chromium.swt#73]
hello there

i tryed to use your libs in oxygen and than in photon.
till know i only made it work in photon.

my question is bcs i am new to the supject is:
  is it possible to use your lib in older versions of eclipse like oxygen ?

kind regards

**Comment by kenrachynski** [comment]
No. This will only work on Eclipse Photon (Eclipse Platform 4.8). I would like to say "or later" but I don't know that answer. As of this comment, Eclipse 2019-03 (Eclipse Platform 4.11) is the current platform available.

**Comment by gzunino** [comment]
@Falafelrollo @kenrachynski  We have removed JNR dependency in 0.10.0. There are no specific dependencies to any eclipse version or API. This should work with any recent version, Oxygen included.
