### ISSUE TITLE
Browser functions should persist changing domain to replicate default SWT browser behaviour.

### ISSUE THREAD

**Issue by alanmitic** [maketechnology/chromium.swt#76]
The browser functions seem to get removed when we change domain.

So for chromium.swt:
•	Create browser component.
•	Register browser functions,
•	Go to some page.  (Browser functions are present).
•	Go to another page on in a different domain.  (Browser functions are no longer present).

For default SWT browser:
•	Create browser component.
•	Register browser functions,
•	Go to some page.  (Browser functions are present).
•	Go to another page on in a different domain.  (Browser functions are present).

The test snippet loads a tester page that dumps the browser functions and attempts to execute the registered on.   Then it move to another domian then comes back and the browser function is no longer present.
[BFIssue.zip](https://github.com/maketechnology/chromium.swt/files/3391906/BFIssue.zip)

**Comment by gzunino** [comment]
Closing for now, it can be improved with a newer cef version, now with current version. Provided example can work with minimal modification (deferring the java function call a few milliseconds for example).
