### ISSUE TITLE
Could not find resourceswt-chromium-0100 on windows

### ISSUE THREAD

**Issue by ChristophKaser** [maketechnology/chromium.swt#77]
When I try to use the new release (v0.10.0) on windows, I get the following exception:

```
java.lang.UnsatisfiedLinkError: Could not find resourceswt-chromium-0100 (in subdirectory: chromium-3071 )
	at org.eclipse.swt.internal.chromium.ResourceExpander.findResource(ResourceExpander.java:119)
	at org.eclipse.swt.chromium.Chromium.loadLib(Chromium.java:1655)
	at org.eclipse.swt.chromium.Chromium.<clinit>(Chromium.java:103)
	at org.eclipse.swt.chromium.Browser.<init>(Browser.java:32)

```

So I looked at the code trying to load the library in the debugger and found that it tries to load 
swt-chromium-0100-gtk.dll instead of swt-chromium-0100-win32.dll

The reason is that the compiler has inlined the constant Platform.PLATFORM and you built the packages on linux.

I will create a PR for this.

**Comment by vel144** [comment]
As mentioned, changed the Platform.PLATFORM to SWT.getPlatform() to load swt-chromium-01000-win32.dll. After that i get the below exception,

\chromium-3071\chromium_swt_0100.dll: %1 is not a valid Win32 application

What is the issue here?

**Comment by gzunino** [comment]
I have published new version of the p2 repo with the fix. I don't see any issue loading libraries now.

**Comment by gzunino** [comment]
I also uploaded a binary sample app for testing: 
https://github.com/maketechnology/chromium.swt/releases/tag/example.win
If you still have problems please try deleting ~/.swt folder
