### ISSUE TITLE
How can I pass parameters to browser?

### ISSUE THREAD

**Issue by mifritscher** [maketechnology/chromium.swt#96]
On the swing-based jcef, parameters can be passed to the cef: 
https://medium.com/@daniel.bischoff/integrating-chromium-as-a-web-renderer-in-a-java-application-with-jcef-72f67a677db6

```
final CefApp cefApp = CefApp.getInstance(new String[]{"-–disable-web-security"});
```

it seems to use a ```CefAppHandlerAdapter```, which implements ```onBeforeCommandLineProcessing``` . I couldn't a way to archive this with chromium.swt :-(

Any hints?

**Comment by mifritscher** [comment]
OK, sort of progress.

In ```initCEF()``` (Chromium.java), I added

```
                Callback on_before_command_line_processing_cb = new Callback(Chromium.class, "on_before_command_line_processing", void.class, new Type[] {long.class,long.class});
                app.on_before_command_line_processing = checkGetAddress(on_before_command_line_processing_cb);
```
, with a simple
```
    static void on_before_command_line_processing(long para1,long para2) {
    	System.out.println("survived " + para1 + " " + para2);
    }
```

It works, I get the ```survived 2694721801792 0``` .

So, now I need to work with the parameters (2x long are certainly wrong). on JCEF, is is defined as ```    public void onBeforeCommandLineProcessing(String process_type, CefCommandLine command_line) {
``` 

The right signature seems to be ```virtual void OnBeforeCommandLineProcessing( const CefString& process_type, CefRefPtr< CefCommandLine > command_line )
``` ( https://magpcss.org/ceforum/apidocs3/projects/%28default%29/CefApp.html ), on https://bitbucket.org/chromiumembedded/java-cef/src/master/java/org/cef/handler/CefAppHandlerAdapter.java a usage example can be found.

I'm afraid that the current callback methods can't cope with this callback signature? Is there any other way?

**Comment by gzunino** [comment]
Hi, this project is not a general purpose CEF binding for java/swt. It's an implementation of the Chromium SWT widget using CEF. So, CEF APIs are not exposed.

**Comment by mifritscher** [comment]
the thing is that with this commandline options you can control also the rendering and behavior. E.g wether 3D acceleration should be used. In my use case, I need it for the option "--touch-events", so that the elements in the browser widget can be used by fingers as well. Or is there another way to archieve this?

**Comment by mifritscher** [comment]
Another useful option would be e.g. unsafely-treat-insecure-origin-as-secure for deep-embedded environments.
